# Generated by Django 5.1.7 on 2025-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="first_page",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
