# Generated by Django 5.1.7 on 2025-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_document_first_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='game_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='first_page',
            field=models.TextField(),
        ),
    ]
