# backend/Dockerfile.web
FROM python:3.11-slim

WORKDIR /app

# 移除：不再需要编译 mysqlclient，因为我们改用了 pymysql
# pkg-config, default-libmysqlclient-dev, build-essential 是必须的
COPY requirements.txt .
# RUN apt-get update && apt-get install -y \
#     pkg-config \
#     default-libmysqlclient-dev \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*


RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn NoteCraft_backend.wsgi:application --bind 0.0.0.0:8000"]