# Generated by Django 5.1.7 on 2025-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
